name: CI Docker Build and Push


on:
  push:
    branches:
      - main


jobs:
  build-and-push:
    runs-on: ubuntu-latest


    steps:
      # Étape de checkout du code source
      - name: Checkout code
        uses: actions/checkout@v3


      # Étape de build Maven pour générer le fichier WAR
      - name: Build with Maven
        run: mvn clean package
      
      # Connexion à Docker Hub
      - name: Log in to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: echo "${DOCKER_HUB_TOKEN}" | docker login -u "${}" --password-stdin


      # Construction de l'image Docker avec le fichier WAR généré
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/tempactivite:latest


      # Pousse l'image Docker sur Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/tempactivite:latest
